### ISSUE TITLE
need an example dataset

### ISSUE THREAD

**Issue by drj11** [mikecroucher/Code_cafe#1]
As per the syllabus, I was thinking one dataset that is built-in, and one that is downloaded.

I'm On my phone, but from the built-in datasets R package the airquality dataset looks okay.

**Comment by mikecroucher** [comment]
How about taking the artificial data I created for http://www.walkingrandomly.com/?p=5254 and putting it into a .csv file? 

If I host the .csv on WalkingRandomly, we can show people how to download it to personal machine and do a .csv import from a local file. 

Could also do an example that pulls directly off the web.

Finally, there's a worked-example of non-linear curve fitting right there, ready to go.

**Comment by mikecroucher** [comment]
Sounds good to me. If I recall correctly, it's a nice one for kmeans clustering demo.

**Comment by mikecroucher** [comment]
Additionally, by giving students info on all available built in datasets, they are free to go off-piste and follow their interests if they wish. 

Working on a little something right now....

**Comment by willfurnass** [comment]
Would be good for demoing plotting etc but also potentially discussing different approaches to classification.  Sounds like it's less useful for clustering as [feature labels are needed to clearly distinguish two species](https://en.wikipedia.org/wiki/Iris_flower_data_set).  

Could export another dataset (e.g. air quality) as a CSV (and possibly dirty it up) to demo importing and cleaning data.

**Comment by drj11** [comment]
I would urge restraint. We are probably not going to be classifying.

**Comment by mikecroucher** [comment]
Agreed. Baby steps
